version: "3.9"

services:
  baget:
    image: loicsharma/baget
    container_name: ddd.baget
    env_file: ./Infrastructure/baget/baget.env
    volumes:
      - ./Infrastructure/baget/data:/var/baget
    ports:
      - "5555:80"

  papercut:
    image: jijiechen/papercut
    container_name: ddd.papercut
    ports:
      - "25:25"
      - "37408:37408"

  seq:
    image: datalust/seq
    container_name: ddd.seq
    env_file: ./Infrastructure/seq/seq.env
    volumes:
      - ./Infrastructure/seq/data:/data
    ports:
      - "5566:80" # UI & ingestion
      - "5567:5341" # ingestion only

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ddd.rabbitmq
    env_file: ./Infrastructure/rabbitmq/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"

  vetclinicpublic:
    build:
      context: ./VetClinicPublic/src/VetClinicPublic
      network: host
